### ISSUE TITLE
.NET Core SDK adoption blockers

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vs-validation#5]
This issue tracks the adoption blocker issues to switching to the .NET Core project system in VS2017:

## Functional issues

* [X] https://github.com/AArnott/Nerdbank.GitVersioning/issues/93 Nerdbank.GitVersioning interop with .NET SDK
* [x] https://github.com/dotnet/sdk/issues/703 DocumentationFile cannot be set in project file
* [x] https://github.com/dotnet/sdk/issues/651 AssemblyInfo.cs should not be generated on package restore
* [x] XLF -> resx generation support (ideally via full Multilingual App Toolkit support)
* [x] [ReadOnlySourceTree package support in](https://github.com/dotnet/sdk/issues/887) and for .NET SDK
* [X] MicroBuild signing plugin support in and for .NET SDK
* [x] Get unit tests running at least on net45 if not also netcoreapp1.0
* [x] Verify that pdbgit works properly
* [x] https://github.com/onovotny/MSBuildSdkExtras/issues/6 Get nupkg lib folders right.
* [ ] Must be able to run Microsoft ship requirement set of FxCop rules ([FxCop port](https://github.com/dotnet/roslyn-analyzers/tree/master/docs/FxCopPort))
* [ ] Totally portable toolset so it can run without VS2017 installation, *or* VS2017 installed on MicroBuild agents

## Reliability issues

* [x] https://github.com/dotnet/roslyn/issues/16410 VS crashes on open of .NET Core projects far too frequently
* [x] https://github.com/dotnet/roslyn/issues/16673 VS crashes when SolutionCreator.UpdateDocumentAsync gets NullReferenceException back over jsonrpc
* [x] https://github.com/NuGet/Home/issues/4289 PackTask frequently fails with file access conflict 

## Non-blocking (because some workaround exists) but tracking
* [ ] https://github.com/dotnet/roslyn-project-system/issues/88 Analyzers aren't listed for customization in Solution Explorer
* [ ] https://github.com/NuGet/Home/issues/4125 PackageReference should support DevelopmentDependency metadata
* [ ] https://github.com/NuGet/Home/issues/4649 PackTask throws NRE when NuspecProperties are specified.
* [ ] https://github.com/NuGet/Home/issues/4698 NuGet pack should include satellite assemblies
* [x] https://github.com/dotnet/corefx/issues/16596 TraceListeners don't allow our unit tests to verify calls.
